---
name: Build zulip

"on":
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'certbot-deplo-hook'
      - 'custom_zulip_files'
      - '.github/workflows/build-container.yaml'

jobs:
  build-zulip:
    runs-on: ubuntu-latest
    steps:
      - name: Clone current repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/tibeer/zulip:9.2
